---
title: "Week-7: Code-Along (Challenge 7)"
author: "Yang Juan Hun"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=TRUE,echo=TRUE}
# load packages
# install.packages("palmerpenguins")
library(tidyverse)
library(palmerpenguins)
glimpse(penguins)
```

```{r, eval=TRUE,echo=TRUE}
# recreate penguin plot
ggplot(data = penguins,
 mapping = aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 labs(title = "Bill depth and length",
 subtitle = "Dimensions for Adelie, Chinstrap, and Gentoo Penguins",
 x = "Bill depth (mm)", y = "Bill length (mm)",
 colour = "Species",
 caption = "Source: Palmer Station LTER / palmerpenguins package") +
 scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# omit data and mapping argument names
ggplot(penguins,
 aes(x = bill_depth_mm,
 y = bill_length_mm,
 colour = species)) +
 geom_point() +
 scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# alternative formatting
ggplot(penguins) + # Data layer
 aes(x = bill_depth_mm, 
 y = bill_length_mm,
 colour = species) + # Aesthetics layer 
 geom_point() + # Geometric layer
 scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# mapping colour, shape, size and alpha to different variables
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, colour = species,
 shape = species, size = body_mass_g, alpha = flipper_length_mm)) +
 geom_point() + scale_colour_viridis_d()
```

```{r, eval=TRUE,echo=TRUE}
# mapping vs setting
# mapping
ggplot(penguins) +
 aes(x = bill_depth_mm,
 y = bill_length_mm,
 size = body_mass_g,
 alpha = flipper_length_mm) +
 geom_point()

# setting
ggplot(penguins) + 
 aes(x = bill_depth_mm, 
 y = bill_length_mm) + 
 geom_point(size = 2, alpha = 0.5)
```

```{r, eval=TRUE,echo=TRUE}
# faceting

#species against island
ggplot(penguins) +
 aes(x = bill_depth_mm, 
 y = bill_length_mm) + 
 geom_point() +
 facet_grid(species ~ island)

#species against sex
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(species ~ sex)

# sex against species
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(sex ~ species)

# species only
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species)

# species only, two columns
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_wrap(~ species, ncol = 2)

# species only using facet_grid
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm)) + geom_point() +
 facet_grid(. ~ species)
```

```{r, eval=TRUE,echo=TRUE}
# facet and colour
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d()

# facet and colour sans legend
ggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
 geom_point() + facet_grid(species ~ sex) + scale_color_viridis_d() +
 guides(color = "none")
```

```{r, eval=TRUE,echo=TRUE}
# load packages
# install.packages("openintro")
library(openintro)
glimpse(loans_full_schema)
```

```{r, eval=TRUE,echo=TRUE}
# select variables
loans <- loans_full_schema %>%
 select(loan_amount, interest_rate, term, grade, 
 state, annual_income, homeownership, debt_to_income)
glimpse(loans)
```

```{r, eval=TRUE,echo=TRUE}
# histogram
ggplot(loans) + aes(x = loan_amount) +
 geom_histogram()

# binwidth = 1000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 1000)

# binwidth = 5000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 5000)

# binwidth = 20000
ggplot(loans, aes(x = loan_amount)) +
 geom_histogram(binwidth = 20000)
```

```{r, eval=TRUE,echo=TRUE}
# customizing histograms
ggplot(loans, aes(x = loan_amount)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)", y = "Frequency", title = "Amounts of Lending Club loans" )
```

```{r, eval=TRUE,echo=TRUE}
# fill with categorical variable
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_histogram(binwidth = 5000, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans")
```

```{r, eval=TRUE,echo=TRUE}
# facet with categorical variable
ggplot(loans, aes(x = loan_amount, fill = homeownership)) + geom_histogram(binwidth = 5000) +
 labs(x = "Loan amount ($)",y = "Frequency",title = "Amounts of Lending Club loans") +
 facet_wrap(~ homeownership, nrow = 3)
```

```{r, eval=TRUE,echo=TRUE}
# density plots
ggplot(loans, aes(x = loan_amount)) +
 geom_density()

# bandwidth = 0.5
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 0.5)

# bandwidth = 1 (default bandwidth)
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 1)

# bandwidth = 2
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2)
```

```{r, eval=TRUE,echo=TRUE}
# customizing density plots
ggplot(loans, aes(x = loan_amount)) +
 geom_density(adjust = 2) +
 labs( x = "Loan amount ($)", y = "Density", title = "Amounts of Lending Club loans" )
```

```{r, eval=TRUE,echo=TRUE}
# adding categorical variables
ggplot(loans, aes(x = loan_amount, fill = homeownership)) +
 geom_density(adjust = 2, alpha = 0.5) +
 labs(x = "Loan amount ($)",y = "Density",title = "Amounts of Lending Club loans", fill = "Homeownership")
```

```{r, eval=TRUE,echo=TRUE}
# box plots
ggplot(loans, aes(x = interest_rate)) +
 geom_boxplot()
```

```{r, eval=TRUE,echo=TRUE}
# box plot with outliers
ggplot(loans, aes(x = annual_income)) +
 geom_boxplot()
```

```{r, eval=TRUE,echo=TRUE}
# customizing box plots
ggplot(loans, aes(x = interest_rate)) +geom_boxplot() +labs(x = "Interest rate (%)",y = NULL,
 title = "Interest rates of Lending Club loans") +
 theme( axis.ticks.y = element_blank(), axis.text.y = element_blank() )
```

```{r, eval=TRUE,echo=TRUE}
# adding categorical variables to box plots
ggplot(loans, aes(x = interest_rate,
 y = grade)) +
 geom_boxplot() +
 labs(x = "Interest rate (%)",y = "Grade",title = "Interest rates of Lending Club loans",subtitle = "by grade of loan")
```

```{r, eval=TRUE,echo=TRUE}
# scatterplots
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
 geom_point()
```

```{r, eval=TRUE,echo=TRUE}
#install packages
# install.packages("hexbin")
library(hexbin)

# hex plots
ggplot(loans, aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()

# filtered hex plot
ggplot(loans %>% filter(debt_to_income < 100), 
 aes(x = debt_to_income, y = interest_rate)) +
 geom_hex()
```

```{r, eval=TRUE,echo=TRUE}
# bar plot
ggplot(loans, aes(x = homeownership)) +
 geom_bar()

# segmented bar plot
ggplot(loans, aes(x = homeownership, 
 fill = grade)) +
 geom_bar()

## segmented bar plot based on percentage
ggplot(loans, aes(x = homeownership, fill = grade)) +
 geom_bar(position = "fill")
```

```{r, eval=TRUE,echo=TRUE}
# customising bar plots
ggplot(loans, aes(y = homeownership, fill = grade)) + geom_bar(position = "fill") +
labs( x = "Proportion", y = "Homeownership", fill = "Grade", title = "Grades of Lending Club loans", subtitle = "and homeownership of lendee")
```

```{r, eval=TRUE,echo=TRUE}
# violin plots
ggplot(loans, aes(x = homeownership, y = loan_amount)) +
 geom_violin()
```

```{r, eval=TRUE,echo=TRUE}
# ridge plots
# install.packages("ggridges")
library(ggridges)
ggplot(loans, aes(x = loan_amount, y = grade, fill = grade, color = grade)) + 
 geom_density_ridges(alpha = 0.5)

```
